### ISSUE TITLE
Interest using a func in GaugeRepository

### ISSUE THREAD

**Issue by BoBoByOneKenobi** [AnthonyGiretti/Angular5-RealTime-gauges-with-SignalR-Core-EFCore2#1]
Just to understand, why using a Func in GaugeRepository, Func<GaugeContext> instead of GaugeRepository ?

**Comment by AnthonyGiretti** [comment]
I use Func to inject a new instance of DbContext , because  lifeCycle objects in DI must in be in singleton, and I don't want to inject a DbContext in Singleton. So everything is in Singleton except DbContext

**Comment by AnthonyGiretti** [comment]
thank you for your question
